secret:
  create: false
  existingName: safespot-secret

apiCore:
  image:
    tag: local
    pullPolicy: IfNotPresent

apiPublicRead:
  image:
    tag: local
    pullPolicy: IfNotPresent

externalIngestion:
  image:
    tag: local
    pullPolicy: IfNotPresent

nginx:
  image:
    tag: local
    pullPolicy: IfNotPresent

autoscaling:
  apiCore:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

  apiPublicRead:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

  externalIngestion:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70