secret:
  create: false
  existingName: safespot-secret
apiCore:
  image:
    repository: ghcr.io/project-safespot/safespot-api-core
    tag: 3d32a27
    pullPolicy: Always
apiPublicRead:
  image:
    repository: ghcr.io/project-safespot/safespot-api-public-read
    tag: 3d32a27
    pullPolicy: Always
externalIngestion:
  image:
    repository: ghcr.io/project-safespot/safespot-external-ingestion
    tag: 3d32a27
    pullPolicy: Always
nginx:
  image:
    repository: ghcr.io/project-safespot/safespot-nginx
    tag: b07c93f
    pullPolicy: Always