apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-core
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app: api-core
    env: dev
    region: ap-northeast-2
spec:
  selector:
    matchLabels:
      app: api-core
      env: dev
  namespaceSelector:
    matchNames:
      - application
  endpoints:
    - targetPort: 8080
      path: /actuator/prometheus
      interval: 15s
