apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: async-worker
  namespace: {{ .Values.safespot.namespace.monitoring }}
  labels:
    release: kube-prometheus-stack
    app: async-worker
    env: {{ .Values.safespot.env }}
    region: {{ .Values.safespot.region }}
spec:
  selector:
    matchLabels:
      app: async-worker
      env: {{ .Values.safespot.env }}
  namespaceSelector:
    matchNames:
      - {{ .Values.safespot.namespace.application }}
  endpoints:
    - port: {{ .Values.safespot.metrics.asyncWorker.port }}
      path: {{ .Values.safespot.metrics.asyncWorker.path }}
      interval: {{ .Values.safespot.metrics.asyncWorker.interval }}
