{{- if .Values.redisExporterExternalServiceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter-external
  namespace: {{ .Values.safespot.namespace.monitoring }}
  labels:
    release: kube-prometheus-stack
    app: redis-exporter
    env: {{ .Values.safespot.env }}
    region: {{ .Values.safespot.region }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-redis-exporter
      app.kubernetes.io/instance: redis-exporter
  namespaceSelector:
    matchNames:
      - exporter
  endpoints:
    - targetPort: 9121
      path: /metrics
      interval: 30s
{{- end }}
