apiVersion: v2
name: safespot-ops
description: SafeSpot Observability Helm Chart (dashboards, servicemonitors, prometheusrules)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: "84.1.2"
    repository: "https://prometheus-community.github.io/helm-charts"
