{{- if .Values.safespot.externalSecrets.grafanaAdmin.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: {{ .Values.safespot.namespace.monitoring }}
  labels:
    app: safespot-observability
    env: {{ .Values.safespot.env }}
spec:
  refreshInterval: {{ .Values.safespot.externalSecrets.grafanaAdmin.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.safespot.externalSecrets.grafanaAdmin.secretStoreRef.name }}
    kind: {{ .Values.safespot.externalSecrets.grafanaAdmin.secretStoreRef.kind }}
  target:
    name: {{ .Values.safespot.externalSecrets.grafanaAdmin.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.safespot.externalSecrets.grafanaAdmin.userKey }}
      remoteRef:
        key: {{ .Values.safespot.externalSecrets.grafanaAdmin.adminUserParameter }}
    - secretKey: {{ .Values.safespot.externalSecrets.grafanaAdmin.passwordKey }}
      remoteRef:
        key: {{ .Values.safespot.externalSecrets.grafanaAdmin.adminPasswordParameter }}
{{- end }}
