apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: api-public-read
    release: {{ .Release.Name }}
  # -----------------------------------------------------------------------
  # sync-wave: 1
  # Deployment(wave 2) 보다 먼저 생성하여 ClusterIP 확보
  # -----------------------------------------------------------------------
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave.service | quote }}

spec:
  type: {{ .Values.service.type }}
  selector:
    app: api-public-read
    release: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http