apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-ingestion
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: safespot
    tier: ingestion
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: safespot

  source:
    repoURL: https://github.com/project-safespot/safespot-k8s.git
    targetRevision: main
    path: apps/external-ingestion

  destination:
    server: https://kubernetes.default.svc
    namespace: application

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: batch
      kind: CronJob
      jsonPointers:
        - /status/lastScheduleTime