apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: safespot
    tier: data
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: safespot

  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: "19.6.4"
      helm:
        valueFiles:
          - $values/data/redis/values.yaml
    - repoURL: https://github.com/project-safespot/safespot-k8s.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: safespot-cache

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates