apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: api-core
    release: {{ .Release.Name }}
  # -----------------------------------------------------------------------
  # sync-wave: -1
  # Deployment(wave 2) 보다 먼저 생성되어야
  # envFrom.configMapRef 참조 시 Pod 생성 실패 방지
  # -----------------------------------------------------------------------
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave.configmap | quote }}

data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}